// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeAppz(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3B_F-lIvU9HK2YiYAmRJqLa4QcqorKHI',
    appId: '1:224673754882:web:ecef76d9f9453f63745c1b',
    messagingSenderId: '224673754882',
    projectId: 'app-reservation-de-ressources',
    authDomain: 'app-reservation-de-ressources.firebaseapp.com',
    storageBucket: 'app-reservation-de-ressources.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw1NmtLQIi7zVNBsI9EEfgtIhOGJRA_lY',
    appId: '1:224673754882:android:5f968f0594fa928a745c1b',
    messagingSenderId: '224673754882',
    projectId: 'app-reservation-de-ressources',
    storageBucket: 'app-reservation-de-ressources.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwBqxZ8amkcC5rrAX1Ecsu5XvtGrw7zv8',
    appId: '1:224673754882:ios:be2788008b6ab2c9745c1b',
    messagingSenderId: '224673754882',
    projectId: 'app-reservation-de-ressources',
    storageBucket: 'app-reservation-de-ressources.firebasestorage.app',
    iosBundleId: 'com.example.applicationDeReservationDeRessources',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwBqxZ8amkcC5rrAX1Ecsu5XvtGrw7zv8',
    appId: '1:224673754882:ios:be2788008b6ab2c9745c1b',
    messagingSenderId: '224673754882',
    projectId: 'app-reservation-de-ressources',
    storageBucket: 'app-reservation-de-ressources.firebasestorage.app',
    iosBundleId: 'com.example.applicationDeReservationDeRessources',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3B_F-lIvU9HK2YiYAmRJqLa4QcqorKHI',
    appId: '1:224673754882:web:5384752f8db47b1e745c1b',
    messagingSenderId: '224673754882',
    projectId: 'app-reservation-de-ressources',
    authDomain: 'app-reservation-de-ressources.firebaseapp.com',
    storageBucket: 'app-reservation-de-ressources.firebasestorage.app',
  );

}